\input texinfo @c -*-texinfo-*- 
@c %**start of header
@setfilename octopus.info 
@settitle @code{octopus} manual
@c %**end of header


@dircategory Individual utilities
@direntry
* octopus: (octopus).           The octopus program.
@end direntry


@c ***************SUMMARY DESCRIPTION AND COPYRIGTH**********************
@ifinfo
The purpose of this info file is describing how to use
the octopus program.

Copyright 2002 M. A. L. Marques, Alberto Castro and Angel Rubio

Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.
     
@ignore
Permission is granted to process this file through TeX
and print the results, provided the printed document
carries a copying permission notice identical to this
one except for the removal of this paragraph (this
paragraph not being relevant to the printed manual).
@end ignore

Permission is granted to copy and distribute modified
versions of this manual under the conditions for
verbatim copying, provided also that the section
entitled ``Copying'' and ``GNU General Public License''
are included exactly as in the original, and provided
that the entire resulting derived work is distributed
under the terms of a permission notice identical to this
one.

Permission is granted to copy and distribute
translations of this manual into another language,
under the above conditions for modified versions,
except that this permission notice may be stated in a
translation approved by the Free Software Foundation.

@end ifinfo
@c **********************************************************************



@c ***************TITLE PAGE AND COPYRIGHT*******************************
@titlepage

@title @code{octopus} manual
@subtitle Electronic Structure
@subtitle Molecular Dynamics
@subtitle Recipes-Generator
@subtitle March 2002
@sp 5
@image{octosex,8cm,}
@center Male Hapalochlaena lunulata (top),
@center and female Hapalochlaena lunulata (bottom).
@center Photograph by Roy Caldwell.
@author By Miguel A. L. Marques, Alberto Castro and Angel Rubio

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2002 M. A. L. Marques, Alberto Castro and Angel Rubio
@vskip 24pt
This program, along with its documentation, is free software;
you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public
License along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
@vskip 24pt
Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.
     
Permission is granted to copy and distribute modified
versions of this manual under the conditions for
verbatim copying, provided also that the section
entitled ``Copying'' and ``GNU General Public License''
are included exactly as in the original, and provided
that the entire resulting derived work is distributed
under the terms of a permission notice identical to this
one.
     
Permission is granted to copy and distribute
translations of this manual into another language,
under the above conditions for modified versions,
except that this permission notice may be stated in a
translation approved by the Free Software Foundation.
@end titlepage
@c **********************************************************************

@iftex
@headings off
@c @evenheading @thispage{}            @| @thistitle @| @image{octosex,1.7cm}
@c @oddheading  @image{octosex,1.75cm} @| @thischapter  @| @thispage{} 
@evenheading @thispage{}            @| @thistitle @|
@oddheading  @| @thischapter  @| @thispage{} 
@end iftex



@c ***************TOP NODE AND MASTER MENU*******************************
@ifinfo
@node Top, Copying, (dir), (dir)
@c    Node name,  next         , previous , up
@top octopus
@c The purpose of this info file is describing how to use
@c the octopus program. This is obvious, I know, but texinfo manual
@c encourages to put something over here.
@end ifinfo

@ifhtml
@image{octosex,8cm}
@center Male Hapalochlaena lunulata (top),
@center and female Hapalochlaena lunulata (bottom).
@center Photograph by Roy Caldwell.
@end ifhtml

@menu
* Copying::                     
* Authors::                     
* Introduction::                
* Installation::                
* The input file::              
* A word about units::          
* Variable Index::              

@detailmenu
 --- The Detailed Node Listing ---

Description of input options

* The parser::                  
* Input file options::          

Input file options

* Generalities::                
* Species::                     
* Coordinates::                 
* Velocities::                  
* States::                      
* xx::                          

@end detailmenu
@end menu

@c **********************************************************************






@c ***************THE BODY OF THE DOCUMENT*******************************

@c **********************************************************************
@c ***************COPYING************************************************
@c **********************************************************************
@node Copying, Authors, Top, Top
@chapter Copying

  This programs is
"free"; this means that everyone is free to use it and free to
redistribute it on a free basis.
What is not allowed is to try to prevent others from further sharing
any version of this program that they might get from you.

  Specifically, we want to make sure that you have the right to give
away copies of the program, that you receive
source code or else can get it if you want it, that you can change this
program or use pieces of them in new free programs, and that you know
you can do these things.

  To make sure that everyone has such rights, we have to forbid you to
deprive anyone else of these rights.  For example, if you distribute
copies of the program, you must give the recipients all
the rights that you have.  You must make sure that they, too, receive or
can get the source code.  And you must tell them their rights.

  Also, for our own protection, we must make certain that everyone finds
out that there is no warranty for this program.
If these programs are modified by someone else and passed on, we want
their recipients to know that what they have is not what we distributed,
so that any problems introduced by others will not reflect on our
reputation.

  The precise conditions of the license 
are found in the General Public
Licenses that accompany it.
@c **********************************************************************
@c **********************************************************************
@c **********************************************************************


@c **********************************************************************
@c ********************AUTHORS, COLLABORATORS AND ACKNOWLEDGEMENTS*******
@c **********************************************************************
@node Authors, Introduction, Copying, Top
@chapter Authors, Collaborators and Acknowledgements.

The main developing team of the first version of this program is
made up of Miguel A. L. Marques and Angel Rubio, working at the Donostia
International Physics Center (San Sebastian, Espa@~na), and Alberto
Castro, who works at the University of Valladolid, Departamento de
Fisica Teorica. The code is a major remake of a previous version written
by the same team, and this one in turn was developed as an extension
of a linear optical response code written by George F. Bertsch, K. Yabana
and Angel Rubio.

If you have some time free, and if you feel like taking a joy ride with
FORTRAN 90, just drop us an @email{marques@@nautilus.fis.uc.pt, email}. You can
also send us patches, comments, ideas, wishes, etc.

@c **********************************************************************
@c **********************************************************************
@c **********************************************************************



@c **********************************************************************
@c ********************* INTRODUCTION ***********************************
@c **********************************************************************
@node Introduction, Installation, Authors, Top
@c    node-name,     next,          previous,     up
@chapter Introduction

     
@code{octopus} @footnote{
@emph{octopus}: Etymology: New Latin @emph{Octopod-}, @emph{Octopus}, 
from Greek @emph{oktOpous}.
Any of a genus (@emph{Octopus}) of cephalopod mollusks that have 
eight muscular arms equipped with two rows of suckers; 
broadly, any octopod excepting the paper nautilus.
Something that resembles an octopus especially in having many 
centrally directed branches.
(taken from the Merryam-Webster's dictionary.)
}
is a program aimed at the ab initio virtual experimentation on 
a hopefully ever increasing range of systems types. Its 
main characteristics are:

@itemize @bullet
@item Electrons are describe quantum-mechanically within the
Density-Functional Theory (DFT), in its time-dependent form (TDDFT)
when doing simulations in time. Nuclei are described classically
as point particles. 
@item Electron-nucleus interaction is described within the
Pseudopotential approximation..
@end itemize
@c **********************************************************************
@c **********************************************************************
@c **********************************************************************



@c **********************************************************************
@c *************************INSTALLATION*********************************
@c **********************************************************************
@node Installation, The input file, Introduction, Top
@chapter Installation

For the impatients, here goes the quickstart: 
@example
tar -cd octopus<-version>.tar.gz
cd octopus-<version>
./configure
make
make install
@end example

This will probably @strong{not} work, so before giving up, just read
the following paragraphs.

The code is written in standard Fortran 90, with a couple of routines
in C (and in bison, if we count the input parser). To build it
you will need both a C compiler (@code{gcc} works just fine), and a
Fortran 90 compiler. No free Fortran 90 compiler is available yet,
so, if you want to chew the @code{octopus}, you will have either
to help the @code{g95} project @uref{http://g95.sourceforge.net}
or pay some money.

Besides the compilers, you will still need
@enumerate
@item
@code{make} :  Version 3.79 or higher of the GNU @code{make} 
  should work, any other @emph{could} work, but maybe not.
@item
@code{cpp} : The C preprocessor is heavily used in @code{octopus}.
  GNU @code{cpp} is just fine, but any @code{cpp} that accepts
  the @code{-C} flag (preserve comments) should work just fine.
@item
FFTW : In principle @code{octopus} can live without FFTW, but he will
  feel somehow weaker. Just grab this great library from @uref{http://www.fftw.org/}
@item
LAPACK/BLAS : Not heavily used, but required. If you are running Linux,
there is a fair change they are already installed in your system. The same
goes to the more heavyweight machines (alphas, IBMs, SGIs, etc). Otherwise,
just grab the source from @uref{http://www.netlib.org}.
@item
GSL : Finally that someone had the nice idea of making a public scientific
  library! GSL still needs to grow, but it is already quite useful and impressive.
  @code{octopus} uses splines, complex numbers, special functions, etc. from GSL,
  so it is a must! If you don't have it already installed in your system, you can
  obtain FFTW from @uref{http://sources.redhat.com/gsl/}. You will need version 1.0 
  or higher.
@item
MPI : If you want to run @code{octopus} in multi-tentacle (parallel) mode,
  you will need an implementation of MPI. @code{mpich} 
  (@code{http://www-unix.mcs.anl.gov/mpi/mpich/}) works just fine in our
  Linux boxes.
@end enumerate

First you should obtain the code gzipped-tarred file @code{octopus<-version>.tar.gz} 
(this you probably have already done). The code is freely available, and
can be downloaded from @uref{http://www.tddft.org/programs/octopus}. There exits
a @code{cvs} server, but it currently does not have anonymous access. You
can nevertheless browse the repository in 
@uref{http://nautilus.fis.uc.pt/cgi-bin/cvsweb.cgi/marques/octopus/}. Uncompress
and untar it (@code{gzip -cd octopus<-version>.tar.gz | tar -xvf -}).
In the following, @code{OCTOPUS-HOME} denotes the home directory of
octopus, created by the @code{tar} command.

The @code{OCTOPUS-HOME} contains the following subdirectories:
@itemize
@item
@code{doc} : The documentation of @code{octopus} in @emph{texinfo} format.
@item
@code{liboct} : Small C library that handles the interface to
  GSL and the parsing of the input file. It also contains some assorted
  routines that we didn't want to write in boring Fortran.
@item
@code{src} : Fortran 90 source files. Note that these have to be preprocessed
  before being fed to the Fortran compiler, so do not be scared by
  all the # directives.
@code{samples} : Sample input files for @code{octopus}
@end itemize

Before configuring you can (should) setup a couple of options. Although
the configure script tries to guess your system settings for you, we recommend 
that you set explicitly the default Fortran 90 compiler and the compiler options. In
@code{bash} you would tipically do:
@example
export F90=abf90
export F90FLAGS="-YEXT_NAMES=LCS -YEXT_SFX=_"
@end example
If you are compiling in an alpha, or in some other system with proprietary
LAPACK/BLAS support, you should also set the @code{LIB_LAPACK} variable:
@example
export LIB_LAPACK="-lcxml"
@end example

You can now run the configure sript (@code{./configure}). You can use
a fair amount of options to spice (@code{octopus}) to your own taste.
To obtain a full list just type @code{./configure --help}. Some 
commonly used options include:
@itemize
@item
@code{--prefix=PREFIX} : Change the base instalation dir of @code{octopus}
  to @code{PREFIX}. The executable will be installed in @code{PREFIX/bin},
  the libraries in @code{PREFIX/lib} and the documentation in @code{PREFIX/info}.
@item
@code{--with-fftw=DIR} : Instalation directory of the FFTW library.
@item
@code{--with-lapack=DIR} : Instalation directory of the LAPACK and
  BLAS libraries.
@item
@code{--with-gsl=DIR} : Instalation directory of the GSL library. The
  libraries are expected to be in @code{DIR/lib} and the include
  files in @code{DIR/include}
@item
@code{--enable-1d} : Build the 1d version of @code{octopus}. This option
  turns off @code{--enable-3d}, etc.
@item
@code{--enable-3d} : Build the 3d version of @code{octopus}. This is the
  default behaviour.
@end itemize

Run @code{make}, and the @code{make install}. If everything went fine, you
should now be able to taste @code{octopus}.

The program has been tested in the following platforms:
@itemize
@item
@code{i686-pc-linux-gnu} : with the @uref{http://www.absoft.com, Absoft}
  compiler.
@end itemize
If you manage to compile/run @code{octopus} in a different platform,
or with a different compiler, please let us know so we can update the
list. Patches to solve compiler issues are also welcomed.

Build the documentation in the format you prefer. Since you are reading
this, you already have it in some format. Due to the power of @code{texinfo},
a series of formats are available, namely @code{dvi}, @code{html},
@code{pdf} and @code{info}. You simply have to @code{cd} to @code{OCTOPUS-HOME/doc}
and @code{make <format>}. The @code{info} file may be read by the @code{info}
program by typing @code{info -f octopus.info}, or alternatively may
be installed in your general @code{info} structure by typing 
@code{make install}.

@c **********************************************************************
@c **********************************************************************
@c **********************************************************************



@c **********************************************************************
@c *******************DESCRIPTION OF INPUT OPTION************************
@c **********************************************************************
@node The input file, A word about units, Installation, Top
@c    node-name,     next,          previous,     up
@chapter Description of input options

@menu
* The parser::                  
* Input file options::          
@end menu

@node The parser, Input file options, The input file, The input file
@section The parser

All input options should be in a file called "@code{inp}", in the
directory @code{octopus} is run from. For a fairly comprehensive
example, just look at the file @code{OCTOPUS_HOME/samples/inp}

At the begining of the program @code{liboct} reads in the @code{inp}
file, parses it, and generates a list of variables that will be
read by @code{octopus} (note that the input is case independent). 
There are two kind of variables, scalar
values (strings or numbers), and blocks (that you may view as
matrices). A scalar variable @code{var} can be defined by:
@example
var = exp
@end example
@code{var} can contain any alphanumeric character plus "_", and 
@code{exp} can be a quote delimited string, a number (integer,
real, or complex), a variable name, or a mathematical expression. 
In the expression all arithmetic operators are supported 
("a+b", "a-b", "a*b", "a/b"; for exponenciation the C syntax
"a^b" is used), and the following functions can be use:
@itemize
@item @code{sqrt(x)} : The square root of @code{x}.
@item @code{exp(x)} : The exponential of @code{x}.
@item @code{log(x)} or @code{ln(x)}: The natural logarith of @code{x}.
@item @code{log10(x)} : Base 10 logarith of @code{x}.
@item @code{sin(x)}, @code{cos(x)}, @code{tan(x)}, @code{cot(x)},
  @code{sec(x)}, @code{csc(x)}: The sinus, cosinus, tangent, cotangent,
  secant and cosecant of @code{x}.
@item @code{asin(x)}, @code{acos(x)}, @code{atan(x)}, @code{acot(x)},
  @code{asec(x)}, @code{acsc(x)}: The inverse (arc-) sinus, cosinus, tangent, cotangent,
  secant and cosecant of @code{x}.
@item @code{sinh(x)}, @code{cosh(x)}, @code{tanh(x)}, @code{coth(x)},
  @code{sech(x)}, @code{csch(x)}: The hyperbolic sinus, cosinus, tangent, cotangent,
  secant and cosecant of @code{x}.
@item @code{asinh(x)}, @code{acosh(x)}, @code{atanh(x)}, @code{acoth(x)},
  @code{asech(x)}, @code{acsch(x)}: The inverse hyperbolic sinus, cosinus, tangent, cotangent,
  secant and cosecant of @code{x}.
@end itemize
You can also use any of the predefined variables:
@itemize
@item @code{pi} : 3.141592653589793, what else is there to say?
@item @code{e} : The base of the natural logarithms.
@item @code{false} or @code{f} or @code{no} : False in all its flavors. For the
  curious, @code{false} is defined as 0.
@item @code{true} or @code{t} or @code{yes} : The truthful companian of @code{false}. For the
  curious, @code{true} is defined as 1.
@end itemize

Blocks are defined as a collection of values, organized in row and column format.
The syntax is the following:
@example
%var
  exp | exp | exp | ...
  exp | exp | exp | ...
  ...
%
@end example
Rows in a block are separated by a newline, while columns are
separated by the character "|". There may be any number of lines and any
number of columns block. Note also that each lines can have a different
number of columns.

If @code{octopus} tries to read a variable that is not defined in the
@code{inp} file, it automatically assigns to it a default value. All
variables read are output to the file @code{out.oct}. If you are
not sure of what the program is reading, just take a look at it.
Everything following the character "#" until the end of the line
is simply cast into oblivion.

@node Input file options,  , The parser, The input file
@section Input file options

@code{octopus} has quite a few options, that we will subdivide in different groups.
After the name of the option, its type and default value (when appliable)
are given in parentesis.

@menu
* Generalities::                
* Species::                     
* Coordinates::                 
* Velocities::                  
* States::                      
* xx::                          
@end menu

@node Generalities, Species, Input file options, Input file options
@subsection Generalities

@itemize @bullet
@item @vindex @code{Verbose}
  @code{Verbose} (integer, 30) : 
  Verbosity level of the program. The higher the
  more verbose @code{octopus} is. Current levels are:
  @itemize @minus
    @item @code{verbose <=  0} : Silent mode. No output except fatal errors.
    @item @code{verbose >   0} : Warnings only.
    @item @code{verbose >  20} : Normal program info.
    @item @code{verbose > 999} : Debug mode. Issues a message everytime the
      program enters a (important) subroutine, and prints the time it spend upon return.
  @end itemize

@item @vindex @code{SystemName}
  @code{SystemName} (string, 'system') :
  A string that identifies the current run. This parameter is used 
  to build the names of the files generated by @code{octopus}
  (@code{SystemName.restart}, @code{SystemName.mult}, etc).

@item @vindex @code{CalculationMode}
  @code{CalculationMode} (integer, 1) :
  It defines the type of simulation to perform. Options are:
  @itemize @minus
    @item @code{1} : Start static calculation.
    @item @code{2} : Resume static calculation.
    @item @code{3} : Calculate unocuppied states.
    @item @code{4} : Resume calculation of unocuppied states.
    @item @code{5} : Start time-dependent propagation.
    @item @code{6} : Resume time-dependent propagation.
    @item @code{7} : Start static polarizability calculation.
    @item @code{8} : Resume static polarizability calculation.
    @item @code{9} : Perform Born-Oppenheimer MD simulation
    @item @code{99} : Prints out an octopus recipe
  @end itemize

@item @vindex @code{Units}
@vindex @code{UnitsInput}
@vindex @code{UnitsOutput}
@code{Units} (string, 'a.u'):
  Atomic units seem to be the preferred system in the atomic and
  molecular physics community, despite the opinion of some of the authors
  of this program. Accordingly, atomic units can be used both for
  input and output. However, some people like using eV for energies and @AA{} 
  for lengths. This other system of units (the @emph{convenient system}, 
  in words of Prof. George W. Bertsch), can also be used. 
  Valid options are:
  @itemize @minus
    @item @code{'a.u'} : atomic units
    @item @code{'eVA'} : electron-volts/amstrongs
  @end itemize

  @xref{A word about units}, for detailed information about units. Two other 
  input variables are possible: @code{UnitsInput}, and @code{UnitsOutput},
  if different units are desired for input and output.

@end itemize

@node Species, Coordinates, Generalities, Input file options
@subsection Species

@itemize @bullet
@item @vindex @code{Species}
@code{Species} (block data) : 
  A specie is by definition an ion (nucleus + core electrons) described
  through a pseudopotential, or an external potential (until now,
  only jellium spheres and point charges are implemented).
  The format of this block is different for 1 or 3 dimensions, and
  can be best understood through examples. In 1D, e.g.
  @example
    %Species
      'H'       |  1.0079 | 2.0 |  1.0
    %
  @end example
  This defines a species labeled '@code{H}' of weight @code{1.0079},
  nuclear charge @code{2.0}, and valence charge @code{1.0}. The potential
  used in 1D calculations is the soft-Coulomb potential Z/sqrt(x*x + 1).
  In 3D, e.g.
  @example
    %Species
      'O'       | 15.9994 | 8   |  1   | 1
      'H'       |  1.0079 | 1   |  0   | 0
      'jelli01' | 23.2    | 8.0 |  5.0
      'point01' | 32.3    | 2.0   
    %
  @end example
  In this case, we have 4 "species" present:
  @itemize @minus
  @item Oxygen labeled '@code{O}', to be read from a pseudopotential file
    name @code{O.vps}. Numbers following the label describe 
    succesively the weight, the nuclear charge, the maximum 
    @emph{l}-component of the pseudopotential to consider in the
    calculation, and the @emph{l}-component to consider as local.
  @item Hydrogen defined in the same way as Oxygen.
  @item All species whose label starts by 'jelli' are jellium spheres.
    The other parameters are the weight, the nuclear charge, and the
    valence charge of the sphere.
  @item All species whose label starts by 'point' are point charges.
    The other parameters are the weight and the nuclear charge. In
    fact, point charges are implemented as @emph{rather small} jellium
    spheres, with zero valence charge.
  @end itemize
@end itemize

@node Coordinates, Velocities, Species, Input file options
@subsection Coordinates

@itemize @bullet
@item @vindex @code{PDBCoordinates}
@code{PDBCoordinates} (string, 'coords.pdb') :
  Tries to read the atomic coordinates from the file @code{PDBCoordinates}.
  The PDB (@uref{http://www.rcsb.org/pdb/,Protein Data Bank}) format is
  quite complicated, and it goes well beyond the scope of this manual. You
  can find a comprehensive description in 
  @uref{http://www.rcsb.org/pdb/docs/format/pdbguide2.2/guide2.2_frame.html}.
  From the plethora of instructions defined in the PDB standard, @code{octopus}
  only reads 2, @code{ATOM} and @code{HETATOM}. From these fields, it reads:
  @itemize @minus
  @item columns 13-16 : The specie; in fact @code{octopus} only cares about the first
    letter -- 'CA' and 'CB' will both refer to Carbon -- so elements whose
    chemical symbol has more than one letter can not be represented in this way.
    So, if you want to run mercury ('Hg') please use one of the other two methods
    to input the atomic coordinates, @code{XYZCoordinates} or @code{Coordinates}.
  @item columns 18-21 : The residue. If residue is 'QM', the atom is treated
    in Quantum Mechanics, otherwise it is simply treated as an external classical
    point charge. Its charge will be given by columns 61-65.
  @item columns 31-54 : The cartesian coordinates. The Fortran format is
    @code{'(3f8.3)'}.
  @item columns 61-65 : Classical charge of the atom. The Fortran format is
    @code{'(f6.2)'}.
  @end itemize

@item @vindex @code{XYZCoordinates}
@code{XYZCoordinates} (string, 'coords.xyz') :
  If @code{PDBCoordinates} is not present, reads the atomic coordinates
  from the XYZ file @code{XYZCoordinates}. The XYZ format is very simple,
  as can be seem by this example for the CO molecule (in @AA{}).
  @example
    2
      CO molecule in equilibrium
    C  -0.56415   0.0   0.0
    O   0.56415   0.0   0.0
  @end example
  The first line of the file has an integer indicating the number of
  atoms. The second can contain comments that are simply ignored by 
  @code{octopus}. Then there follow one line per each atom containing
  the chemical species and the cartesian coordinates of the atom.

@item @vindex @code{Coordinates}
@code{Coordinates} (block data) :
  If neither a @code{XYZCoordinates} or a @code{PDBCoordinates} was found,
  @code{octopus} tries to read the coordinates for the atoms from the
  block @code{Coordinates}. The format is quite straightforward:
  @example
    %Coordinates
      'C' | -0.56415 | 0.0 | 0.0 | no
      'O' |  0.56415 | 0.0 | 0.0 | no
    %
  @end example
  The first line defines a Carbon atom at coordinates (@code{-0.56415},
  @code{0.0}, @code{0.0}), that is @emph{not} allowed to move during
  dynamical simulations. The second line has a similar meaning. This
  block obviously defines a Carbon monoxide molecule, if the input
  units are @AA{}.

@item @vindex @code{AdjustCoordinates}
@code{AdjustCoordinates} (logical, false) :
  If true applies a translates the atom coordinates so that the
  geometrical center of the molecule coincides with the zero of 
  the mesh, and rotates them, fixing the largest dimension
  of the molecule to the axis defined through @code{MainAxis}.
  Very useful when handling large and elongated molecules -- try
  it out!

@item @vindex @code{MainAxis}
@code{MainAxis} (block data) :
  Defines the axis to be used if @code{AdjustCoordinates} is true.
  If not set defaults to the z axis.

@item @vindex @code{OutputCoordinates}
@code{OutputCoordinates} (logical, false) :
  If true @code{octopus} outputs a XYZ file called 
  '@code{SystemName}.xyz' containing the coordinates of the atoms
  treated within Quantum Mechanics. If point charges were defined
  in the PDB file (see @code{PDBCoordinates}), they will be output
  in the file '@code{SystemName}_classical.xyz'.
@end itemize

@node Velocities, States, Coordinates, Input file options
@subsection Velocities

@itemize @bullet
@item @vindex @code{XYZVelocities} :
@code{XYZVelocities} (string, 'velocities.xyz') :
  @code{octopus} will try to read the starting coordinates of the atoms from the XYZ file 
  @code{XYZVelocities}.

@item @vindex @code{Velocities}
@code{Velocities} (block data) :
  If @code{XYZVelocities} is not present, @code{octopus} will try fetch the initial 
  atomic velocities from this block. If this block is not present, @code{octopus}
  will reset the initial velocities to zero. The format of this block can be
  illustrated by this example:
  @example
    %Velocities
      'C'  | -1.7 | 0.0 | 0.0
      'O'  |  1.7 | 0.0 | 0.0
    %
  @end example
  It describes one Carbon and one Oxygen moving at the relative
  velocity of @code{3.4} velocity units.
@end itemize

@node States, xx, Velocities, Input file options
@subsection States

@itemize @bullet
@item @vindex @code{SpinComponents}
@code{SpinComponents} (integer, 1) :
  Defines the spin mode @code{octopus} will run in. Valid modes are:
  @itemize @minus
    @item @code{1} : Spin-unpolarized calculation.
    @item @code{2} : Spin-polarized calculation (collinear spin). This mode
      will double the number of wavefunctions necessary for a spin-unpolarized 
      calculation.
    @item @code{4}: Non-collinear spin. This mode will double the number 
      of wavefunctions necessary for a spin-unpolarized calculation, and each of
      the wavefunctions will be a 2-spinor.
  @end itemize

@item @vindex @code{NumberKPoints}
@code{NumberKPoints} (integer, 1) :
  If @code{octopus} was compiled for periodic systems, the number of
  @emph{k} points to use in the calculation. If @code{NumberKPoints = 1},
  use only the Gamma point.

@item @vindex @code{ExcessCharge}
@code{NumberKPoints} (double, 1) :
  The net charge of the system. A negative value means that we are adding 
  electrons, while a positive value means we are taking electrons
  away from the system.

@item @vindex @code{EmptyStates}
@code{EmptyStates} (integer, 1) :
  How many unoccupied states to use in the ground-state
  calculation. Note that this number is unrelated to @code{CalculationMode = 4}.

@item @vindex @code{Occupations}
@code{Occupations} (blockdata) :
  The occupation numbers of the orbitals can be fixed through the use of this
  variable. For example:
  @example
    %Occupations
      2.0 | 2.0 | 2.0 | 2.0 | 2.0
    %
  @end example
  would fix the occupations of the five states to @code{2.0}. There must be
  as many columns as states in the calculation. If @code{SpinComponents = 2}
  this block should contain two lines, one for each spin channel.
  This variable is very useful when dealing with highly symmetric small systems
  (like an open shell atom), for it allows us to fix the occupation numbers
  of degenerate states in order to help @code{octopus} to converge.
@end itemize

@node xx,  , States, Input file options
@subsection xx

@itemize @bullet
@end itemize

The real-space mesh is an equally-spaced one, although the spacings maybe
different for each direction. The shape of the simulation region may also
be tuned to suit the geometric configuration of the system.

@node A word about units, Variable Index, The input file, Top
@appendix A word about units

@c **********************************************************************



@c ***************THE END OF THE DOCUMENT********************************
@node    Variable Index,  , A word about units, Top
@c       node-name,    next, previous,     up
@unnumbered Variable Index
     
@printindex vr
     
@contents

@bye
@c **********************************************************************
