\input texinfo @c -*-texinfo-*- 
@c %**start of header
@setfilename octopus.info 
@settitle @code{octopus} manual
@c %**end of header


@dircategory Individual utilities
@direntry
* octopus: (octopus).           The octopus program.
@end direntry


@c ***************SUMMARY DESCRIPTION AND COPYRIGTH**********************
@ifinfo
The purpose of this info file is describing how to use
the octopus program.

Copyright @copyright{} not settled down yet.

Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.
     
@ignore
Permission is granted to process this file through TeX
and print the results, provided the printed document
carries a copying permission notice identical to this
one except for the removal of this paragraph (this
paragraph not being relevant to the printed manual).
     
@end ignore
Permission is granted to copy and distribute modified
versions of this manual under the conditions for
verbatim copying, provided also that the section
entitled ``Copying''
is included exactly as in the original, and provided
that the entire resulting derived work is distributed
under the terms of a permission notice identical to this
one.

Permission is granted to copy and distribute
translations of this manual into another language,
under the above conditions for modified versions,
except that this permission notice may be stated in a
translation.

@end ifinfo
@c **********************************************************************



@c ***************TITLE PAGE AND COPYRIGHT*******************************
@titlepage
@c @sp 10
@c @c The title is printed in a large font.
@c @center @titlefont{@code{octopus} manual}
@c @image{octosex,8cm}
@c @center Male Hapalochlaena lunulata (top),
@c @center and female Hapalochlaena lunulata (bottom).
@c @center Photograph by Roy Caldwell.
@c @c The following two commands start the copyright page.
@title @code{octopus} manual
@subtitle Electronic Structure, Molecular Dynamics and Recipes-Generator.
@c @subtitle SECOND-SUBTITLE
@sp 5
@image{octosex,8cm}
@author By Miguel A. L. Marques, Alberto Castro and Angel Rubio


@page
@vskip 0pt plus 1filll
Copyright @copyright{} not settled down yet.

Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.
     
Permission is granted to copy and distribute modified
versions of this manual under the conditions for
verbatim copying, provided also that the section
entitled ``Copying''
is included exactly as in the original, and provided
that the entire resulting derived work is distributed
under the terms of a permission notice identical to this
one.
     
Permission is granted to copy and distribute
translations of this manual into another language,
under the above conditions for modified versions,
except that this permission notice may be stated in a
translation.
@end titlepage
@c **********************************************************************

@iftex
@headings off
@c @evenheading @thispage{}            @| @thistitle @| @image{octosex,1.7cm}
@c @oddheading  @image{octosex,1.75cm} @| @thischapter  @| @thispage{} 
@evenheading @thispage{}            @| @thistitle @|
@oddheading  @| @thischapter  @| @thispage{} 
@end iftex



@c ***************TOP NODE AND MASTER MENU*******************************
@ifinfo
@node Top, Copying, (dir), (dir)
@c    Node name,  next         , previous , up
@top octopus
The purpose of this info file is describing how to use
the octopus program. This is obvious, I know, but texinfo manual
encourages to put something over here.
@end ifinfo

@menu
* Copying::                     
* Introduction::                
* Compilation::                 
* Description of input options::  
* Units::                       
* Concept Index::               

@detailmenu
 --- The Detailed Node Listing ---

Description of input options

* Generalities::                
* Describing the species::      
* Describing the atoms::        
* Describing the electrons::    
* Mesh parameters::             
* Self-consistent cycle::       
* Time evolution::              

@end detailmenu
@end menu

@c **********************************************************************






@c ***************THE BODY OF THE DOCUMENT*******************************

@node Copying, Introduction, Top, Top
@chapter Copying

We have not settled down yet the legal details of the code. Eventually it
will be GPLed, but since the code is not working yet, you basically
have not the right to copy, modify, etc, which you wouldn't want to do it
anyhow.


@node Introduction, Compilation, Copying, Top
@c    node-name,     next,          previous,     up
@chapter Introduction

     
@code{octopus} @footnote{
From latin @emph{octopus}, set of animals belonging to the...
}
is a program aimed at the ab initio virtual experimentation on 
a hopefully ever increasing range of systems types. Its 
main characteristics are:

@itemize @bullet
@item Electrons are describe quantum-mechanically within the
Density-Functional Theory (DFT), in its time-dependent form (TDDFT)
when doing simulations in time. Nuclei are described classically
as point particles. 
@item Electron-nucleus interaction is described within the
Pseudopotential approximation..
@end itemize

@node Compilation, Description of input options, Introduction, Top
@chapter Compilation

The variables in the file @code{Make.arch} must be adapted to the computer,
compiler, preprocessor, etc. @code{arch} must be the output to the
"@code{uname -m}" command. Occasionally you may need to change variable
definitions in the first lines of the @code{Makefile}.

The variable @code{FORLIBS}, to be defined in @code{Make.arch}, contains
all the libraries that must be linked with the rest of the code. It must
contain, at least:

@code{FORLIBS = -ldrfftw -ldfftw -lblas -llapack -lgslcblas -lgsl -loct}

That is, inclusion of the FFTW@footnote{
@code{www.fftw.org}}
package libraries, BLAS/LAPACK@footnote{
@code{www.netlib.org}}
libraries, and the GNU Scientific Library @code{gsl}@footnote{
@code{www.gnu.org}}. All these libraries are GPLed and
freely distributed. The @code{-loct} links the @code{liboct.a} library,
which is compiled previous to the main code when issuing
@code{make}.


@node Description of input options, Units, Compilation, Top
@c    node-name,     next,          previous,     up
@chapter Description of input options

The full description of the system to simulate on, and of the simulation
to perform, is done in a file called "inp" that must be present in
the directory where the @code{octopus} command is issued.
The reading of the options is done through the @code{fdf} package,
so the input format must follow its rules. The best thing to do
is to follow the @code{inp} example in @code{OCTOPUS_HOME/samples}
 directory.

@menu
* Generalities::                
* Describing the species::      
* Describing the atoms::        
* Describing the electrons::    
* Mesh parameters::             
* Self-consistent cycle::       
* Time evolution::              
@end menu

@node Generalities, Describing the species, Description of input options, Description of input options
@section Generalities


@subsection @code{Verbose}
@cindex @code{Verbose}
Integer number that sets the level of verbosity of the program:
@itemize @bullet
@item @code{>999} : Debug mode, maximum verbosity.
@item @code{>20}  : Normal program info.
@item @code{>0}   : Just warnings.and errors
@item @code{<=0}  : Silent, only fatal errors.
@end itemize
@emph{Default: 30}

@subsection @code{SystemName}:
@cindex @code{SystemName}
A string of characters that is used to build the filenames 
(@code{SystemName.restart}, @code{SystemName.mult}, etc).

@emph{Default: sysname.}

@subsection @code{CalculationMode}:
@cindex @code{CalculationMode}
Integer number. It defines the type of simulation to perform. Options are:
@itemize @bullet
@item @code{1} : Start static calculation
@item @code{2} : Resume static calculation
@item @code{3} : calculate unocuppied states
@item @code{4} : resume unocuppied states calculation
@item @code{5} : start td
@item @code{6} : resume td
@item @code{7} : start static polarizability
@item @code{8} : resume static polarizability
@item @code{9} : perform Born-Oppenheimer MD
@item @code{99} : prints out the "Pulpo a Feira" recipe
@end itemize
@emph{Default: 1.}

@subsection @code{Units}:
@cindex @code{Units}
Atomic units seem to be the preferred system in the atomic and
molecular physics community, despite the opinion of some of the authors
of this program. Accordingly, atomic units may be used for describing
input and output magnitudes. However, some people like using eV
for energies and @AA{}  for lengths, and this defines a new units system
(the @emph{convenient system}, in words of Prof. George W. Bertsch),
which can also be used due to inheritance reasons. Thus the options 
for this descriptor are:
@itemize @bullet
@item @code{a.u} : atomic units
@item @code{eVA} : electron-volts/amstrongs
@end itemize
@emph{Default: a.u}

@xref{Units} for detailed information about units. Two other 
input descriptors are possible: @code{UnitsInput}, and @code{UnitsOutput},
if different system units are desired in input or output.
@cindex @code{UnitsInput}
@cindex @code{UnitsOutput}


@node Describing the species, Describing the atoms, Generalities, Description of input options
@section Describing the species

A specie, in principle,is an ion (nucleus + core electrons) described
through a pseudopotential. However, the code allows for jellium 
calculation, in which case the species will be the full jellium
distribution, and point charges - which in fact are no more than
@code{rather small} jellium spheres.

@subsection @code{NumberSpecies}
@cindex @code{NumberSpecies}
Obvious meaning. 

@subsection @code{Species}
@cindex @code{Species}
It is a @code{fdf} block of data which contains the information
about the species. Its format may be illustrated through an example:

@example
%block Species
Na        23.0   11.   2    1
jelli      8.0   8.0   5.0
point      1.0   1.0   
%endblock Species
@end example

In this case, we have three "species" present:
@itemize @bullet
@item A sodium, pseudopotential, labeled "@code{Na}", to be read
from a pseudopotential file. Numbers following the label describe 
succesively the weight, the nuclear charge, the maximum 
@emph{l}-component of the pseudopotential to consider in the
calculation, and the @emph{l}-component to consider as local.
@end itemize



@node Describing the atoms, Describing the electrons, Describing the species, Description of input options
@section Describing the atoms

Atoms may be described in three ways: throuhg a PDB file, through a
XYZ file, or within the @code{fdf inp} file. The program will attempt
the three methods in that order.

@subsection @code{PDBCoordinates}
@cindex @code{PDBCoordinates}
The name of a PDB file describing the atomic positions.
If this is not the format to be used, this descriptor should not 
be present in the @code{fdf} file.

@emph{Default: coords.pdb}

@subsection @code{XYZCoordinates}
@cindex @code{XYZCoordinates}
The name of a XYZ file describing the atomic positions.
If this is not the format to be used, this descriptor should not
be present in the @code{fdf} file.

@emph{Default: coords.xyz}



@node Describing the electrons, Mesh parameters, Describing the atoms, Description of input options
@section Describing the electrons

@node Mesh parameters, Self-consistent cycle, Describing the electrons, Description of input options
@section Mesh parameters

The real-space mesh is an equally-spaced one, although the spacings maybe
different for each direction. The shape of the simulation region may also
be tuned to suit the geometric configuration of the system.

@node Self-consistent cycle, Time evolution, Mesh parameters, Description of input options
@section Self-consistent cycle


@node Time evolution,  , Self-consistent cycle, Description of input options
@section Time evolution

@node Varia, Units, Description of input options, Top


@node Units, Concept Index, Description of input options, Top
@appendix Units

By default, input and output options are describe in atomic units.

@c **********************************************************************



@c ***************THE END OF THE DOCUMENT********************************
@node    Concept Index,  , Units, Top
@c       node-name,    next, previous,     up
@unnumbered Concept Index
     
@printindex cp
     
@contents

@bye
@c **********************************************************************
