@node Undocumented Variables, Examples, Input Variables, Top
@chapter Undocumented Variables

If you want to use these variables you will have to go to the code to find out what they 
do. If you do it, please take the time to write a short description and send a patch of the
manual to us ;) BTW, some of this variables describe things that may not work, or are under
developments, so don't blame us...
@itemize o
@item
  AnimationSampling
@item
  AxisType
@item
  BoundaryZeroDerivative
@item
  CenterOfInversion
@item
  CurrentDFT
@item
  GuessDensityAtomsMagnet
@item
  KineticCutoff
@item
  LB94_beta
@item
  LB94_modified
@item
  LB94_threshold
@item
  OEP_level
@item
  OEP_mixing
@item
  OptControlAlpha
@item
  OptControlEps
@item
  OptControlInitLaser
@item
  OptControlMaxIter
@item
  OutputDuringSCF
@item
  OutputELF_FS
@item
  OutputWfsSqMod
@item
  PeriodicDimensions
@item
  RestartFileFormat
@item
  ShifKPoints
@item
  StaticMagneticField
@item
  TDDeltaStrengthMode
@item
  TDOutputSpin
@item
  VlocalCutoff
@item 
  FromScratch
@end itemize
