#if !defined TEMPLATE_H
#define TEMPLATE_H
#endif
#if !defined UTIL_H
#include "util.h"
#endif

#undef ITEMPLATE_PREFIX
#if defined(TEMPLATE_LEVEL) && defined(TEMPLATE_NAME)
#define ITEMPLATE_PREFIX DECORATE(TEMPLATE_LEVEL,TEMPLATE_NAME)
#elif defined(TEMPLATE_PREFIX)
#define ITEMPLATE_PREFIX TEMPLATE_PREFIX
#elif defined(TEMPLATE_NAME)
#define ITEMPLATE_PREFIX TEMPLATE_NAME
#else
#error "'TEMPLATE_PREFIX' or 'TEMPLATE_NAME' must be defined"
#endif

#undef TEMPLATE
#undef ITEMPLATE_0
#undef ITEMPLATE_1
#undef ITEMPLATE_2

#define TEMPLATE(...) MCASE(ITEMPLATE,__VA_ARGS__)

#define ITEMPLATE_0()

#if defined(ITEMPLATE_PREFIX)
#define ITEMPLATE_1(NAME) DECORATE(ITEMPLATE_PREFIX,NAME)
#else
#define ITEMPLATE_1(NAME) NAME
#endif

#if defined(TEMPLATE_PREFIX)
#define ITEMPLATE_2(LEVEL,NAME) DECORATE(TEMPLATE_PREFIX,NAME)
#else
#if defined(TEMPLATE_NAME)
#define ITEMPLATE_2(LEVEL,NAME) DECORATE(LEVEL,DECORATE(TEMPLATE_NAME,NAME))
#else
#define ITEMPLATE_2(LEVEL,NAME) DECORATE(LEVEL,NAME)
#endif
#endif

#undef IINTERNAL_PREFIX
#if defined(INTERNAL_PREFIX)
#define IINTERNAL_PREFIX INTERNAL_PREFIX
#else
#define IINTERNAL_PREFIX ITEMPLATE_PREFIX
#endif

#undef INTERNAL
#undef IINTERNAL_0
#undef IINTERNAL_1
#undef IINTERNAL_2

#define INTERNAL(...) MCASE(IINTERNAL,__VA_ARGS__)
#define IINTERNAL_0()
#define IINTERNAL_1(NAME) DECORATE(IINTERNAL_PREFIX,DECORATE(i,NAME))
#define IINTERNAL_2(PREFIX,NAME) DECORATE(PREFIX,DECORATE(i,NAME))

#undef IEXTERNAL_PREFIX
#if defined(EXTERNAL_LEVEL) && defined(EXTERNAL_NAME)
#define IEXTERNAL_PREFIX DECORATE(EXTERNAL_LEVEL,EXTERNAL_NAME)
#elif defined(EXTERNAL_LEVEL) && defined(TEMPLATE_NAME)
#define IEXTERNAL_PREFIX DECORATE(EXTERNAL_LEVEL,TEMPLATE_NAME)
#elif defined(EXTERNAL_PREFIX)
#define IEXTERNAL_PREFIX EXTERNAL_PREFIX
#else
#define IEXTERNAL_PREFIX ITEMPLATE_PREFIX
#endif

#undef EXTERNAL
#undef IEXTERNAL_0
#undef IEXTERNAL_1
#undef IEXTERNAL_2

#define EXTERNAL(...) MCASE(IEXTERNAL,__VA_ARGS__)
#define IEXTERNAL_0()
#if defined(IEXTERNAL_PREFIX)
#define IEXTERNAL_1(NAME) DECORATE(IEXTERNAL_PREFIX,NAME)
#else
#define IEXTERNAL_1(NAME) NAME
#endif
#define IEXTERNAL_2(PREFIX,NAME) DECORATE(PREFIX,NAME)

!! Local Variables:
!! mode: f90
!! End:

