#if !defined TEMPLATE_H
#define TEMPLATE_H
#endif
#if !defined UTIL_H
#include "util.h"
#endif
  
#if !defined(TEMPLATE_NAME)
#error "'TEMPLATE_NAME' must be defined"
#endif
  
#undef TEMPLATE
#undef ITEMPLATE_0
#undef ITEMPLATE_1
#undef ITEMPLATE_2
  
#define TEMPLATE(...) MCASE(ITEMPLATE,__VA_ARGS__)
  
#define ITEMPLATE_0()
#define ITEMPLATE_1(NAME) DECORATE(TEMPLATE_NAME,NAME)
#define ITEMPLATE_2(PREFIX,NAME) DECORATE(TEMPLATE_NAME,DECORATE(PREFIX,NAME))
  
#undef INTERNAL
#undef IINTERNAL_0
#undef IINTERNAL_1
#undef IINTERNAL_2
  
#define INTERNAL(...) MCASE(IINTERNAL,__VA_ARGS__)
  
#define IINTERNAL_IMPL(PREFIX,NAME) DECORATE(PREFIX,DECORATE(i,NAME))
  
#define IINTERNAL_0()
#define IINTERNAL_1(NAME) IINTERNAL_IMPL(TEMPLATE_NAME,NAME)
#define IINTERNAL_2(PREFIX,NAME) DECORATE(TEMPLATE_NAME,IINTERNAL_IMPL(PREFIX,NAME))
  
#undef EXTERNAL
#undef IEXTERNAL_0
#undef IEXTERNAL_1
#undef IEXTERNAL_2
  
#if defined(EXTERNAL_NAME)
  
#define EXTERNAL(...) MCASE(IEXTERNAL,__VA_ARGS__)
  
#define IEXTERNAL_0()
#define IEXTERNAL_1(NAME) DECORATE(EXTERNAL_NAME,NAME)
#define IEXTERNAL_2(PREFIX,NAME) DECORATE(EXTERNAL_NAME,DECORATE(PREFIX,NAME))

#endif
  
#undef SPECIAL
#undef ISPECIAL_0
#undef ISPECIAL_1
#undef ISPECIAL_2
#undef ISPECIAL_3
  
#define SPECIAL(...) MCASE(ISPECIAL,__VA_ARGS__)
  
#define ISPECIAL_IMPL(PREFIX,NAME) CONCAT(PREFIX,CONCAT(CONCAT(__,NAME),__))
  
#define ISPECIAL_0()
#define ISPECIAL_1(NAME) ISPECIAL_IMPL(TEMPLATE_NAME,NAME)
#define ISPECIAL_2(PREFIX,NAME) DECORATE(TEMPLATE_NAME,ISPECIAL_IMPL(PREFIX,NAME))
  
!! Local Variables:
!! mode: f90
!! End:
  
  
