#if !defined UTIL_H
#define UTIL_H
#define PROTECT(...) __VA_ARGS__
#define STRING_IMPL(A) #A
#define STRING(A) STRING_IMPL(A)
#define CONCAT_IMPL(A,B) A ## B
#define CONCAT(A,B) CONCAT_IMPL(A,B)
#define DECORATE_IMPL(A,B) A ## _ ## B
#define DECORATE(A,B) DECORATE_IMPL(A,B)
#define APPEND(...) __VA_ARGS__
#define ADD_COMMA(...) ,
#define VA_NUM_ARGS(...) VA_NUM_ARGS_IMPL(__VA_ARGS__,9,8,7,6,5,4,3,2,1)
#define VA_NUM_ARGS_IMPL(D1,D2,D3,D4,D5,D6,D7,D8,D9,N,...) N
#define DECORATION(...) CONCAT(VA_NUM_ARGS(__VA_ARGS__), VA_NUM_ARGS(ADD_COMMA __VA_ARGS__ ()))
#define MCASE(FUNC, ...) MCASE_IMPL(FUNC, DECORATION(__VA_ARGS__))(__VA_ARGS__)
#define MCASE_IMPL(FUNC, DCRT) MCASE_DCRT(DCRT)(FUNC)
#define MCASE_DCRT(DCRT) DECORATE(MACRO,DCRT)
#define MACRO_12(FUNC) DECORATE(FUNC,0)
#define MACRO_11(FUNC) DECORATE(FUNC,1)
#define MACRO_22(FUNC) DECORATE(FUNC,2)
#define MACRO_33(FUNC) DECORATE(FUNC,3)
#define MACRO_44(FUNC) DECORATE(FUNC,4)
#define MACRO_55(FUNC) DECORATE(FUNC,5)
#define MACRO_66(FUNC) DECORATE(FUNC,6)
#define MACRO_77(FUNC) DECORATE(FUNC,7)
#define MACRO_88(FUNC) DECORATE(FUNC,8)
#define MACRO_99(FUNC) DECORATE(FUNC,9)
#endif

!! Local Variables:
!! mode: f90
!! End:

