!! Copyright (C) 2016 X. Andrade
!!
!! This program is free software; you can redistribute it and/or modify
!! it under the terms of the GNU General Public License as published by
!! the Free Software Foundation; either version 2, or (at your option)
!! any later version.
!!
!! This program is distributed in the hope that it will be useful,
!! but WITHOUT ANY WARRANTY; without even the implied warranty of
!! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!! GNU General Public License for more details.
!!
!! You should have received a copy of the GNU General Public License
!! along with this program; if not, write to the Free Software
!! Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
!! 02110-1301, USA.
!!
!! $Id: hardware.F90 11591 2013-12-17 09:10:32Z joseba $

#include "global.h"

module debug_m
  use global_m
  use parser_m
  
  private
  
  public ::             &
    debug_t,            &
    debug_init,         &
    debug_enable,       &
    debug_disable,      &
    debug

  type debug_t
    logical :: info
    logical :: trace
    logical :: trace_term
    logical :: trace_file
    integer :: bits    
  end type debug_t

  type(debug_t), save :: debug
  
contains
  
  subroutine debug_init()

    !%Variable Debug
    !%Type flag
    !%Default no
    !%Section Execution::Debug
    !%Description
    !% This variable controls the amount of debugging information
    !% generated by Octopus. You can use include more than one option
    !% with the + operator.    
    !%Option no 0
    !% (default) <tt>Octopus</tt> does not enter debug mode.
    !%Option info 1
    !% Octopus prints additional information to the terminal.
    !%Option trace 2
    !% Octopus generates a stack trace as it enters end exits
    !% subroutines. This information is reported if Octopus stops with
    !% an error.
    !%Option trace_term 4
    !% The trace is printed to the terminal as Octopus enters or exits subroutines. This slows down execution considerably.
    !%Option trace_file 8
    !% The trace is written to files in the <tt>debug</tt>
    !% directory. For each node (when running in parallel) there is a file called
    !% <tt>debug_trace.&lt;rank&gt;</tt>. Writing these files slows down the code by a huge factor and
    !% it is usually only necessary for parallel runs. In the serial case all
    !% the information can be obtained from standard out.
    !%End
    call parse_variable('Debug', OPTION__DEBUG__NO, debug%bits)

    debug%info = (iand(debug%bits, OPTION__DEBUG__INFO) /= 0)
    in_debug_mode = debug%info

    debug%trace_term = (iand(debug%bits, OPTION__DEBUG__TRACE_TERM) /= 0)
    debug%trace_file = (iand(debug%bits, OPTION__DEBUG__TRACE_FILE) /= 0)
    debug%trace      = (iand(debug%bits, OPTION__DEBUG__TRACE)      /= 0) .or. debug%trace_term .or. debug%trace_file
    
  end subroutine debug_init

  !--------------------------------------------------
  
  subroutine debug_enable()

    debug%info       = .true.
    debug%trace      = .true.
    debug%trace_term = .true.
    debug%trace_file = .true.
    
  end subroutine debug_enable

  !--------------------------------------------------
  
  subroutine debug_disable()

    debug%info = (iand(debug%bits, OPTION__DEBUG__INFO) /= 0)
    in_debug_mode = debug%info

    debug%trace_term = (iand(debug%bits, OPTION__DEBUG__TRACE_TERM) /= 0)
    debug%trace_file = (iand(debug%bits, OPTION__DEBUG__TRACE_FILE) /= 0)
    debug%trace      = (iand(debug%bits, OPTION__DEBUG__TRACE)      /= 0) .or. debug%trace_term .or. debug%trace_file
    
  end subroutine debug_disable
    
  
end module debug_m

!! Local Variables:
!! mode: f90
!! coding: utf-8
!! End:
