#!/bin/bash
#
# $Id$


# Define octopus executables
octopus_exe="octopus octopus_mpi"

# Paths
prefix=/usr
testsuite=$prefix/share/octopus/testsuite

# Arch
arch=${MACHTYPE%-pc-linux-gnu}

# Usage
function usage() {
    cat <<EOF

 Copyright (C) 2005 by Heiko Appel

Usage: oct-run_testsuite [options]
    
     -h            this message
     -n            dry run mode (show what would be executed)
     -s            run short testsuite
     -f            run full testsuite
     -l            local run
     -e            exec suffix for octopus executable
     -p            installation prefix [default: /usr]
     -m address    mail report to address

Report bugs to <appel@physik.fu-berlin.de>.
EOF
 exit 0;
}


# Dry run ...

function CMD {
    [ "$dry_run" -o "$verbose" ] && echo -e "\033[32m$@\033[0m";
    [ ! "$dry_run" ] && eval "$@";
}


# Run all tests

function run_testsuite() {

[ "$local_run" == "yes" ] && testsuite=$(pwd)

for x in $octopus_exe; do
    for y in $(find $testsuite -name "*.test" | xargs grep $match | awk -F: '{print $1}' | sort -u); do
	ybase=`basename $y`
	xybase=${x}${exec_suffix}-${ybase%.test}
	if [ "$local_run" == "yes" ]; then
	    octopus_local=`pwd`/../src/$x
	    [ -x $octopus_local ] && CMD ./oct-run_regression_test.pl -l -p -e $octopus_local -f $y | tee ${xybase}.log
	else
	    [ -x $prefix/bin/${x}${exec_suffix} ] && \
		CMD $prefix/bin/oct-run_regression_test.pl -l -p -e $prefix/bin/$x -s ${exec_suffix} -f $y | tee ${xybase}.log
	fi
	[ -e out.log ] && mv out.log ${xybase}.out.log
    done
done

}


# Send report via mail

function mail_report() {

rm -rf stamp
echo >> stamp
uname -a >> stamp
cat /proc/cpuinfo | grep 'model name' | awk -F: '{print $2}' >> stamp
cat /proc/meminfo | grep MemTotal >> stamp
echo >> stamp


for x in $octopus_exe; do
    for y in $(find $testsuite -name "*.test" | xargs grep $match | awk -F: '{print $1}' | sort -u); do
	ybase=`basename $y`
	xybase=${x}-${ybase%.test}
	failed_tests=$(grep FAIL ${xybase}.log | wc -l) 
	echo "Checking for failed tests: ${xybase}.log"
	if [ $failed_tests -gt 0 ]; then
	    echo "Found: $failed_tests"
	    echo "Mailing report to: $mailaddr"
            cat stamp ${xybase}.log ${xybase}.out.log | mutt -s "[oct-run_testsuite on $arch] daily report" $mailaddr
	fi
    done
done

}


# show usage info if no args at all
[ "$#" -eq 0 ] && usage;

# some defaults
match="short-run"
send_mail="no"

while getopts "hnlsfp:e:m:" opt ; do
    case "$opt" in
        h) usage ;;
        n) echo="echo"; dry_run="yes";; 
        p) prefix="$OPTARG"; testsuite=$prefix/share/octopus/testsuite ;;
        e) exec_suffix="$OPTARG";;
        l) local_run="yes";;
        s) match="short-run" ;;
        f) match="long-run" ;;
        m) mailaddr="$OPTARG"; send_mail="yes" ;;
        ?) echo "Error parsing arguments"; exit 1 ;;
    esac
done
shift $(( OPTIND - 1 ))

# for now the long-run matches everything
[ "${match}" == "long-run" ] && match=.

# run testsuite
run_testsuite $match

# should we send a mail report?
[ "${send_mail}" == "yes" ] && mail_report $match $mailaddr


# clean up
rm -f octopus*.log stamp build-stamp
