#!/bin/bash
#
# $Id$

# Paths
prefix=/usr
testsuite=$prefix/share/octopus/testsuite

# Arch
arch=${MACHTYPE%-pc-linux-gnu}

# Failure reporting.
failed_tests=0
total_tests=0
failure_report=""

# Usage
function usage() {
    cat <<EOF

 Copyright (C) 2005-2006 by Heiko Appel

Usage: oct-run_testsuite [options]
    
     -h            this message
     -n            dry run mode (show what would be executed)
     -s            run short testsuite
     -f            run full testsuite
     -l            local run
     -e            exec suffix for octopus executable
     -p            installation prefix [default: /usr]
     -w            without MPI tests (do not run parallel tests)
     -m address    mail report to address

Report bugs to <appel@physik.fu-berlin.de>.
EOF
 exit 0;
}


# Dry run ...
function CMD {
    [ "$dry_run" -o "$verbose" ] && echo -e "\033[32m$@\033[0m";
    [ ! "$dry_run" ] && eval "$@";
}


# Run all tests
function run_testsuite() {

[ "$local_run" == "yes" ] && testsuite=$(pwd)

for y in $(find $testsuite -name "*.test" | xargs grep $match | awk -F: '{print $1}' | sort -u); do
    total_tests=$((total_tests + 1))
    ybase=`basename $y`
    xybase=${ybase%.test}
    if [ "${local_run}" == "yes" ]; then
	bin_directory=`pwd`/../src
	runtest_directory=$testsuite
    else
	bin_directory=$prefix/bin
	runtest_directory=$bin_directory
    fi
    if [ -n "${exec_suffix}" ]; then
	suffix_opt="-s ${exec_suffix}"
    else
	suffix_opt=""
    fi
    if [ -d "${bin_directory}" ]; then
	CMD $runtest_directory/oct-run_regression_test.pl -l \
	    -p $suffix_opt -D $bin_directory -f $y | \
	    tee ${xybase}.log
	# Look for failed testcases and add to failure summary.
	failures=${PIPESTATUS[0]}
	if [ "${failures}" -ne 0 ]; then
	    failed_tests=$((failed_tests + 1))
	    test_name=`echo $y | sed "s|$testsuite/||"`
	    name_length=`echo -n $test_name | wc -m`
	    space_length=$((50 - name_length))
	    spaces=`for((i = 1; i <= space_length; i++)); do echo -n ' '; done`
	    failure_report="$failure_report    $test_name$spaces$failures\n"
	fi
    fi
    [ -e out.log ] && mv out.log ${xybase}.out.log
done
}


# Send report via mail
function mail_report() {

datestamp=$(date +"%Y-%m-%d")

for y in $(find $testsuite -name "*.test" | xargs grep $match | awk -F: '{print $1}' | sort -u); do
    ybase=`basename $y`
    xybase=${ybase%.test}
    failed_tests=$(grep FAIL ${xybase}.log | wc -l) 
    echo "Checking for failed tests: ${xybase}.log"
    if [ $failed_tests -gt 0 ]; then
	echo "Found: $failed_tests"
	echo "Mailing report to: $mailaddr"
	cat oct-header ${xybase}.log ${xybase}.out.log | mutt -s "[oct-run_testsuite on $arch] daily report - $datestamp" $mailaddr
    fi
done
}


# show usage info if no args at all
[ "$#" -eq 0 ] && usage;


# some defaults
match="short-run"
send_mail="no"

while getopts "hnlsfwp:e:m:" opt ; do
    case "$opt" in
        h) usage ;;
        n) echo="echo"; dry_run="yes";; 
        p) prefix="$OPTARG"; testsuite=$prefix/share/octopus/testsuite ;;
        e) exec_suffix="$OPTARG";;
        l) local_run="yes";;
        s) match="short-run" ;;
        f) match="long-run" ;;
        w) run_in_parallel="no" ;;
        m) mailaddr="$OPTARG"; send_mail="yes" ;;
        ?) echo "Error parsing arguments"; exit 1 ;;
    esac
done
shift $[ OPTIND - 1 ]


# for now the long-run matches everything
[ "${match}" == "long-run" ] && match=.

    
# get epoch seconds at testsuite start
testsuite_start=$(date +%s) 


# run testsuite
run_testsuite $match


# Failure reporting to STDOUT.
if [ $failed_tests -gt 0 ]; then
    echo -e "\033[31m ***** $failed_tests out of $total_tests testfiles failed *****\033[0m"
    echo
    echo "    testfile                                          # failed testcases"
    echo "    --------------------------------------------------------------------"
    echo -e "$failure_report"
    echo -e "\n"
fi    


# get epoch seconds after we are done and compute time difference
testsuite_end=$(date +%s) 
timediff_sec=$[ testsuite_end - testsuite_start ]

rm -rf oct-header
# time calculation stays correct if $timediff_sec < 24h
RUNTIME="Total run-time of the testsuite: $(date +%H:%M:%S -d "00:00:00 + $timediff_sec sec")" 
# save runtime for mail header
echo $RUNTIME > oct-header
echo "" >> oct-header

# and print also to the screen
echo $RUNTIME
echo ""

    
# should we send a mail report?
[ "${send_mail}" == "yes" ] && mail_report $match $mailaddr


# clean up
rm -f octopus*.log stamp build-stamp
