/*
 Copyright (C) 2002 M. Marques, A. Castro, A. Rubio, G. Bertsch

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2, or (at your option)
 any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 02111-1307, USA.
*/
#include "nbo2xyz.h"
#include "../liboct/config.h"

int main( int argc, char **argv )
{
  struct gengetopt_args_info args_info;
  void F90_FUNC_(nbo2xyz, NBO2XYZ) ();
  if (cmdline_parser (argc, argv, &args_info) != 0) exit(1) ;
  F90_FUNC_(nbo2xyz, NBO2XYZ) (&args_info.sampling_arg);
}
/* From now on, the file generated by gengetopt....  The input *.ggo file was:
package "nbo2xyz"
version "no version data"
purpose "From a *.nbo file, it generates a *-movie.xyz file"
option "sampling" s "How often the geometry is sampled." int default="100" yes
*/
/*
  File autogenerated by gengetopt version 2.6  
  generated with the following command:
  gengetopt -Fnbo2xyz --unamed-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* If we use autoconf.  */
/* #ifdef HAVE_CONFIG_H */
/* #include "config.h" */
/* #endif */
/* Check for configure's getopt check result.  */
#ifndef HAVE_GETOPT_LONG
#include "getopt.h"
#else
#include <getopt.h>
#endif

#ifndef HAVE_STRDUP
#define strdup gengetopt_strdup
#endif /* HAVE_STRDUP */

#include "nbo2xyz.h"


void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", PACKAGE, VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
"Purpose:\n"
"  From a *.nbo file, it generates a *-movie.xyz file\n"
"\n"
"Usage: %s [OPTIONS]... [FILES]...\n", PACKAGE);
  printf("   -h      --help          Print help and exit\n");
  printf("   -V      --version       Print version and exit\n");
  printf("   -sINT   --sampling=INT  How often the geometry is sampled. (default=100)\n");
}


/* gengetopt_strdup(): automatically generated from strdup.c. */
/* strdup.c replacement of strdup, which is not standard */
static char *
gengetopt_strdup (const char *s)
{
  char *result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  int c;	/* Character of the parsed option.  */
  int missing_required_options = 0;	

  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->sampling_given = 0 ;
#define clear_args() { \
  args_info->sampling_arg = 100;\
}

  clear_args();

  args_info->inputs = NULL;
  args_info->inputs_num = 0;

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "sampling",	1, NULL, 's' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVs:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          clear_args ();
          cmdline_parser_print_help ();
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          clear_args ();
          cmdline_parser_print_version ();
          exit (EXIT_SUCCESS);

        case 's':	/* How often the geometry is sampled..  */
          if (args_info->sampling_given)
            {
              fprintf (stderr, "%s: `--sampling' (`-s') option given more than once\n", PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->sampling_given = 1;
          args_info->sampling_arg = atoi (optarg);
          break;

        case 0:	/* Long option with no short option */

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          exit (EXIT_FAILURE);

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c\n", PACKAGE, c);
          abort ();
        } /* switch */
    } /* while */

  if (! args_info->sampling_given)
    {
      fprintf (stderr, "%s: `--sampling' (`-s') option required\n", PACKAGE);
      missing_required_options = 1;
    }

  if ( missing_required_options )
    exit (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;

      args_info->inputs_num = argc - optind ;
      args_info->inputs = 
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = strdup (argv[optind++]) ; 
    }

  return 0;
}
