/* nbo2xyz.h */

/* File autogenerated by gengetopt version 2.6  */

#ifndef _nbo2xyz_h
#define _nbo2xyz_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#if defined PACKAGE
#  undef PACKAGE
#endif
#define PACKAGE "nbo2xyz"
#if defined VERSION
#  undef VERSION
#endif
#define VERSION "no version data"

struct gengetopt_args_info {
  int sampling_arg;	/* How often the geometry is sampled. (default=100).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int sampling_given ;	/* Whether sampling was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _nbo2xyz_h */
