!> @file
!!  Performance Data (size of the cache for FFT)
!! @author
!!    Copyright (C) 2009-2011 BigDFT group 
!!    This file is distributed under the terms of the
!!    GNU General Public License, see ~/COPYING file
!!    or http://www.gnu.org/copyleft/gpl.txt .
!!    For the list of contributors, see ~/AUTHORS 

integer, parameter :: ncache_optimal=4*1024 !< value of ncache for the FFT routines

integer, parameter :: timing_flag=0 !< flag that states if we must perform the timings or not
                                    !! definitions of the timing variables just in case


