##############################################################################
# Zoltan Library for Parallel Applications                                   #
# Copyright (c) 2000,2001,2002, Sandia National Laboratories.                #
# This software is distributed under the GNU Lesser General Public License.  #
# For more info, see the README file in the top-level Zoltan directory.      # 
##############################################################################
##############################################################################
# CVS File Information
#    $RCSfile: CVS-HEADER.MAKE,v $
#    $Author: kddevin $
#    $Date: 2006/11/13 18:47:11 $
#    $Revision: 1.6 $
##############################################################################

